version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
