# fly.toml app configuration file generated for whisper-server on 2024-04-09T19:04:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whisper-server'
primary_region = 'ams'

[build]

[[mounts]]
  source = 'app'
  destination = '/whisper_model_persistent'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'a100-80gb'
  memory = '8gb'
  cpu_kind = 'performance'
  cpus = 1
